version: '3.8'

services:
  postgres:
    image: postgres
    container_name: nest-clean-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-clean
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/data/postgres
